### ISSUE TITLE
Adding flag NOGIT to io-package.json required

### ISSUE THREAD

**Issue by mcm1957** [matthsc/ioBroker.gigaset-elements#142]
You decided to not commit the build directory to github. 

There's no rule which required the build directory to be present at github although ist usual provided. Without build directory your adapter cannot be installed directly from github. So its mandatory to add the flag

```
 "nogit": true,
```

to io-package.json.

see https://github.com/ioBroker/ioBroker.admin/blob/1069d2e0514f2a80b4aeeb13806ed9190b0372c4/io-package.json#L184 for an example.

PLEASE ADD AS SOON AS POSSIBLE - a new release is not required as the repositories are reading the info directly from github.

**Comment by matthsc** [comment]
Done
