### ISSUE TITLE
Is this adapetr effected by shutdown of gigaset cloud? Will it work after 29.3.2024?

### ISSUE THREAD

**Issue by mcm1957** [matthsc/ioBroker.gigaset-elements#157]
As gigaset announced a shutdown of gigaset-smart-home-care at 29.3.2024 (https://service.gigaset.com/de/support/solutions/articles/75000121636-deaktivierung-smart-home-care-dienste) please indocate whether this adapter will be affected and stop working at 29.3.2024.

If this adapter is effected, please indicate whether a cloud free solution (local connect) seems to be possible.

If this adapter is dead, please state this and set the repository to archived afterwards.

**Comment by matthsc** [comment]
The adapter does not work anymore after the cloud services have been disabled. To my knowledge there is no way to operate the base station and elements locally.

I'm going to archive this repository.
