### ISSUE TITLE
Cannot find start file

### ISSUE THREAD

**Issue by Voggl93** [matthsc/ioBroker.gigaset-elements#89]
Hallo zusammen

Ich bekomme den Adapter leider nicht zum laufen. 
Kann einer weiterhelfen?
Ich bekomme folgende Fehlermeldung:
startInstance gigaset-elements.0: cannot find start file!

Npm 9.3.1
Nodejs probeweise auf 18.13.0 geupdated aber ohne erfolg

Grüße

**Comment by matthsc** [comment]
Bitte NICHT via Github installieren. Installation ist aktuell nur über latest/beta repository möglich.

**Comment by Voggl93** [comment]
Ah alles klar! Läuft jetzt :)
Wie stehen die Chancen, dass man in Zukunft aktoren auch via ioBroker schalten kann?

**Comment by matthsc** [comment]
An welche Aktoren denkst du dabei? intrusionMode und userAlarm?

**Comment by Voggl93** [comment]
Ne. So wie ich das verstehe kann der Adapter aktuell ja "nur" zustände auslesen. Es gibt ja auch Heizkörperthermostate und Steckdosen im Elements System. Wenn ich die mit dem Adapter Einstellen bzw EIN/AUS schalten könnte wäre das schon geil. Oder geht das in der Aktuellen version schon? Habe aktuell noch keinerlei Sensoren im Haus.

**Comment by matthsc** [comment]
Ahh, verstanden. Da ich weder Thermostate noch Steckdosen habe kann ich das leider nicht selbst reverse engineeren. Melde dich sonst doch direkt bei mir wenn du die Aktoren eingebunden hast, dann können wir das vielleicht in einer Remote Session zusammen anschauen. Ich brauche auf jeden Fall die Ausgabe von [Prepare Test Data](https://github.com/matthsc/ioBroker.gigaset-elements#provide-test-data-for-unsupported-elements) aus dem Admin, und dann müssten wir in der Gigaset Web App schauen, welche Requests beim schalten abgesetzt werden.

**Comment by Voggl93** [comment]
Moin
Ich hab nicht mitbekommen, dass hier noch eine Antwort von dir kam. 
Ich habe aktuell selber auch keine Aktoren im Einsatz. Kann mich aber gerne melden falls es dazu kommen sollte.

**Comment by Voggl93** [comment]
Soo ich bin's wieder :)
Ich hätte mittlerweile ein paar Sensoren Zuhause und auch Steckdosen. Fensterkontakte habe ich allerdings noch von Aqara und bin damit eigentlich relativ zufrieden. 
Falls dein Angebot noch steht könnte ich dir gerne einfach einen Plug zuschicken, sodass du einfach in Ruhe mal schauen kannst ob du den Adapter und die Funktion erweitern kannst. 

LG

**Comment by matthsc** [comment]
Melde dich doch kurz per Email, dann können wir das koordinieren :-)
matthsc gmx.net
